apiVersion: v1
kind: PersistentVolume
metadata:
  name: workloadsapi-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/shared/workloadsapi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workloadsapi-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
#https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-6-adding-health-checks-with-liveness-readiness-and-startup-probes/
#https://dzone.com/articles/health-checks-with-aspnet-core-and-kubernetes

metadata:
  name: workloadsapi
  labels:
    app: workloadsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workloadsapi
  template:
    metadata:
      labels:
        app: workloadsapi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      volumes:
        - name: workloadsapi-storage
          persistentVolumeClaim:
            claimName: workloadsapi-claim
      containers:
      - name: workloadsapi
        image: registry:5000/workloadsapi:latest
        imagePullPolicy: Always
        env:
        - name: NATS__Url
          value: nats://nats.nats.svc:4222
        - name: NATS__Servers__0
          value: nats://nats.nats.svc:4222
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "32Mi"
            cpu: "16m"
          #limits:
          #  memory: "128Mi"
          #  cpu: "512m"
        volumeMounts:
          - mountPath: "/data"
            name: workloadsapi-storage