apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workloadsapi
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "workloadsapi.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: workloadsapi
            port:
              number: 80
