apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: countriesapi-secret
  namespace: countriesapi
spec:
  encryptedData:
    NATS__Servers__0: AgCQKcSuSmeE1Dl16PqdoT28JzkIshvP0ATjoYl+Lgg4oGoPNJTbXbtQljJfgA4Ajtel0UARVpRR3S40FKSqf39Kt4hcuSrcWFI14gYOsez0NPmF59wYpRrzjSUqITUwKbPj0catMNVssCpWJ6UwAvmbyWXXLfMxxKr7zlAKTGlRzoBUElvN6NVcXhxNLxpAoR4bLDwF+tvulFk6ik3AibRykzn8tsZY0cg4716OtwkqOK7DGwrHO2KryPgypswVzcpqZslHJE9Mcer2YgC8B04v+RpLnUd5yR94HcjfafViv+qiaXmaQdCnLCqFYyjvXHmR8u9JaWV6iV0+mOrr4MZaaCORfvOb0idMGulD9yTvsKQtcl9umWWqYiwrueAfHrbKEckfY3IeFG6RWGHmSIHQ8IUzmrBbGXljenlFC+AAF6pzt2ltuE3oLDW7vwAsuL7Lu7O4prj+6zb342YDrjtbf5N7o48ONza1OHmiFzLZBd8bmI1/q1rH1a4Gg7sO0pAMIyiGcs28QwQCdnTVGN4sORZWOV5jJqTTrdkQSoXrAcubCA31cO45HucVIP+ytQX7BZnjfNjFNvK79P0bUIO5XjvQ48bttQybuzCY6tKTJrjwRONbQCPIkujPoeTveayq5WaCYx2kXspvGUY4S6CBQkRTuyccQls90YHIWoDuBPRxP9rkZuqayIkwozXeCSArhKDtsN+k7kKjP2YUSZZSb9SlDeCyF9Gi
    NATS__Url: AgCX0zw6XFGTCeIlXMzZanuldObeWQ47FlcRtxmy1Rnq4Fpos2UYn+EAk/0jdTZibLFcXgbewIkvaGT1e+ECtjpowc4tv9hEjcaUBeMUaXugkxm1skwKAPZR7dRlpFsk2VFrpybQ///VrVMSybfI1cigSI7T4ly8g3mE0iIzvWR8paMskWO8IbtLdb5PasTAjJiqpd5SPgejfnUH13ot1f3B8y2hUd2/pAdmV1ooWn6HxoPPUeOoDa8mp1OoRoMyBX1d1zJEthPJEXTZUVwWIUYeA8WjgQBkuCNN8zdlTnqxtEiCcQsCNwdG5bcAZPomcxmh8VTlsXsGVdzl2MgYms6Np1QyR8zfjb4zSIzfZANABpHdW97EZH1KM+8Oebw1Eb5n/RZ/pLZzgsI0hiEUInIVdgKaemxA7q07Lo8YRIfQpeiIOzz4RRdEAZTzn9NCyobNq/F+nkASM85Y+mr1KQsd5Mxyk9PumysRXU5e98xv/xjfGnT+DXLLrxuti7GdOTEIzBzDIRn6F7Fz+O+MKjYjL1hmItW/pFzxFqgoxnFPisxV41PZR48tf++3HjejJQ4gZR7GIbcUNg1qJgXiend2a7/19pfSX65jelxjzVrtoqB6pi/TwPFBdW29yhYrsU2WJN0a308UAvzxnm8/0i8m3/iwVGcBCy1hjP4f3PAybL118/6cvfpo31OkiU+b/A8RNcUKwnoqPsm2pEtpfOEW0ZmJGYIUSwNj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: countriesapi-secret
      namespace: countriesapi

