version: '3.4'

services:
  workloadsprojector:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - NATS__Servers__0=nats://nats:4222
      - NATS__Url=nats://nats:4222
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - C:/Data/Docker/workloadsprojector:/data/persisted:rw

  workloadsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - NATS__Servers__0=nats://nats:4222
      - NATS__Url=nats://nats:4222
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - C:/Data/Docker/workloadsapi:/data/persisted:rw
 
  nats:
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
