apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
data:
# Put environment variables here that everyone should have
  #NATS__Url: nats://nats.nats.svc:4222
  #NATS__Servers__0: nats://nats.nats.svc:4222
