apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: countriesapi
resources:
- namespace.yaml
- ingress.yaml
- service.yaml
#- secret.yaml
- deployment.yaml
- ../common
images:
- name: registry:5000/countriesapi
  newTag: 1.0.0-dev.1
