apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: countriesapi-secret
  namespace: countriesapi
spec:
  encryptedData:
    NATS__Servers__0: AgA6OMT/xegdGaP87FhESrpLopb6uK0wYiu5/neHP0Ymy0WlKIY3+Occ9dO0lfaGVu2vc4GhESd4HhHXCQ2tgUhX1HNc8Yh6z2V3NpqLzX6QEQg0byo5DgknQCDPBgM2ozY1vJxVOssz61zv7BhhFGB4wsODOyNzIX5HLrD0XBLO5WFPGNUZRxPEROY1FbEjoRC3gxCtOmfkuv/kEYdi9BkYNcPLBYVtaoWVtm8oKPTe8J44hCaiz4ZNAQ+lnXUsAensp8eIMWhf9SjQ+82Z7OC8NBNwDpbskAMFAHekqjMpP5+q8BfuYoAvkyh5A5lOx0gmwaAHbDcO7JSAbCvl5ZZkHWbRByegTSZ0jO89xczXy8PQP0439xOTJE2ZDQFo34tnOEhy16pz9uJ0+Xf2BEgGw/MNaRw/d7RcM2JKdsbi5n3UgeCudUDcR5Sdk29PgcTUahqJQYwmqPtbDTD5TkrykjytLuIt1ynRBDxKoPzQP17V00p+Ugl8T3AKMazmDKyk9MzydWB6sNeOJ7V4f7+MZs+3yro6BOd3hrnqoVEYtFPOw0Jb0Gxz3tHwskUvx9L0sKFve48fXfTMqfcbUB/ROzkv5RRwP2vI8NWc0owmnf4tO63rEsqha1YYX1D+XnSUxYVPGvwIgJc+dgQddFu6dqVkTPOE1IoaEK/3IpNRChKjr9zau78l751zgvkcTSjLC4tCTEY/Gw+UJLP3tdYd7nWSv4n17qlQ
    NATS__Url: AgAdDoPpDicTJufSa1yh1ClZKzLAH84zVziG2zwhtSK+DNppsGjv6sh2m1yeuqtajdEuCTfmcAMz6ZDCdziHwqY/9QPtU/kZ29bW5C13lejLlV8r4XMrHwQfJna/pydFxJxRU2gBOMLe6bjY2lYReUIwNKNZwYgrz80FhD79pgauX0aSdH5gheZiwisq3mILmI73L31y+IEM/zZEESVsqUgf4nqF0tCIqqeag4r2Vsu/KXcdInnQtau2KkJ2rHI0nKxxEqFtHW43kFsK8gHq6WnOF1IzVMyORHABhiSVGRECjvgKDS0b9AK/ze/XeXmWbYWkVDHESzMZoZx+buAStBGsg3Ld1i0boQyNSsaYKc4Pprebi9szVfIk5QaDfb4hJ5W1trcsGHVmwZIl8b0MvR3FN7eM/+1KwU0/tP5u4ioCUxaYxv+aImwsKfOBQetNQorg5hvHh8phCm2HvIFPqIcZIZxtDQTKCwrw8IMGKe/7KuqQBUaohYNp0pJEzBcMrGgJKV2FhANIX6jzlcCjBCDLv/wNiOfz5qdlChupsm1bvKPrPNYw6lpKwZfCCWUKOUGMTkEmK8ZbjOfbaxeoRVEHmyYYJfW0xRcnEdn3mM5RrC+bK/mqt3eGB9kfBwor7EB9gjbaD4vvytqC+UIOMllJ5eshsce6DoMNLkrLPhSazTvAXu90Lja0gM9/0AotnX+k5xA6cznsjoFHM3hW8eeDxymx//c3/UWy
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: countriesapi-secret
      namespace: countriesapi

