apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workloadsprojector

bases:
  - ../common

resources:
  - namespace.yaml
  - ingress.yaml
  - service.yaml
  - secret.yaml
  - deployment.yaml
