apiVersion: v1
kind: PersistentVolume
metadata:
  name: buildversion-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/shared/buildversion"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildversion-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
#https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-6-adding-health-checks-with-liveness-readiness-and-startup-probes/
#https://dzone.com/articles/health-checks-with-aspnet-core-and-kubernetes

metadata:
  name: buildversion
  labels:
    app: buildversion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildversion
  template:
    metadata:
      labels:
        app: buildversion
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      volumes:
        - name: buildversion-storage
          persistentVolumeClaim:
            claimName: buildversion-claim
      containers:
      - name: buildversion
        image: registry:5000/buildversion:latest
        imagePullPolicy: Always
        envFrom:
        #- secretRef: 
        #    name: buildversion-secret
        - configMapRef:
            name: buildversion-configmap
        - configMapRef:
            name: common-configmap
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "32Mi"
            cpu: "16m"
          limits:
            memory: "128Mi"
            cpu: "512m"
        volumeMounts:
          - mountPath: "/data"
            name: buildversion-storage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buildversion-configmap
data:
  DOTNET_ENVIRONMENT: "Production"
  ASPNETCORE_ENVIRONMENT: "Production"
