namespace Workloads.Model
{
    public class Workload
    {
        public Guid WorkloadId { get; set; }
        public DateTimeOffset Start { get; set; }
        public DateTimeOffset? Stop { get; set; }
        public Guid AssignmentId { get; set; }//Foreign Key, not needed, it will be autogenerated but hidden anyways
        public Guid PersonId { get; set; }//Foreign Key, not needed, it will be autogenerated but hidden anyways

        //Browsing properties:
        public virtual Assignment Assignment { get; set; }
        public virtual Person Person { get; set; }
    }
}