apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  concurrencyPolicy: Forbid
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: cronjob
            image: registry:5000/cronjob:latest
          restartPolicy: Never
