apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  schedule: "0 * * * *"
  #https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: cronjob
            image: registry:5000/cronjob:latest
          restartPolicy: Never
